### ISSUE TITLE
Is there a control to upload image in the control

### ISSUE THREAD

**Issue by amitnil-dev** [dynamic-forms/dynamic-forms#294]
I have been playing around with the library. I was trying to create a user registration form where the user can upload a image. Is there any control with type img / img upload.  Or what is the way i can do that.
Great work. Look clean and neat.

**Comment by amitnil-dev** [comment]
how do i do it as i m new to angular

**Comment by amitnil-dev** [comment]
if i m to stupid u can tell me i m okay. just trying.My point being learn, my mail id is amit@versionx.in

**Comment by AlexanderGebuhr** [comment]
@amitnil-dev:  The release of version 15.1.0 includes file uploads. You can have a look at the examples for [@dynamic-forms/material](https://dynamic-forms.azurewebsites.net/v15/examples/material/inputs-variations-file) or [@dynamic-forms/bootstrap](https://dynamic-forms.azurewebsites.net/v15/examples/bootstrap/inputs-variations-file) with variations of file inputs that are supported now. The raw files are available due to the submit event of the form (press the submit button and navigate to files tab) which now has an additional property files (besides value and model) which is a form data object
